package mishpahug.service;

import java.security.Principal;

import mishpahug.domain.StaticFields;
import mishpahug.dto.SuccessResponseDto;
import mishpahug.dto.UserResponseDto;
import mishpahug.dto.UserUpdateDto;

public interface UserService {

	/**
	 * <p>Saves user to the database with login, password and autogenerated timestamp as userId.</p>
	 * @param token - authorization string token 
	 * @return StaticFields - object with list of static fields for profile filling
	 * @throws ConflictException - if user with such login already exists
	 * @throws InvalidDataException
	 * 
	 */
	StaticFields addUser(String token);
	
	/**
	 * <p>Get user profile</p>
	 * @param principal
	 * @return UserResponseDto
	 * @throws ConflictException - Error 409 (empty profile) if user registered on the site but ignored process of filling out the profile form.
	 * @throws UnauthorizedException
	 */
	UserResponseDto getUser(Principal principal);
	
	UserResponseDto login(Principal principal);
	
	UserResponseDto updateUser(UserUpdateDto userUpdateDto, Principal principal);
	
	UserResponseDto deleteUser(Principal principal);
	
	SuccessResponseDto addFirebaseToken(String token, Principal principal);
	
	SuccessResponseDto deleteFirebaseToken(String token, Principal principal);
}
